stages:
  - build
  - deploy
  - release

variables:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"
  PRODUCT: Writerside/pd
  WRS_VERSION: 2.1.1479-p3869
  ARTIFACT: webHelpPD2-all.zip
image: docker.io/library/gradle:8.4.0-jdk17

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .gradle

.build_release:
  stage: build
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  tags:
    - saas-linux-medium-amd64
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  artifacts:
    when: always
    paths:
      - build/distributions/*.zip
      - build/reports/tests
      - build/reports/jacoco/test
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    expire_in: 360 days

.build_artifact:
  stage: build
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  tags:
    - saas-linux-medium-amd64
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    when: always
    paths:
      - build/distributions/*.zip
      - build/reports/tests
      - build/reports/jacoco/test
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    expire_in: 7 days

build_artifact:
  extends: .build_artifact
  script:
    - gradle test
    - gradle -Dversion.prerelease=$CI_PIPELINE_ID-SNAPSHOT buildPlugin

build_release_artifact:
  extends: .build_release
  script:
    - gradle test
    - gradle buildPlugin

build-documentation:
  image: registry.jetbrains.team/p/writerside/builder/writerside-builder:$WRS_VERSION
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - set -e
    - export DISPLAY=:99
    - Xvfb :99 &
    - /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product $PRODUCT --runner gitlab -output-dir public/
    - echo "Test existing of $ARTIFACT artifact"
    - test -e public/$ARTIFACT
  artifacts:
    paths:
      - public/
      - public/$ARTIFACT

pages:
  stage: deploy
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add zip
  script:
    - cp -R build/reports/jacoco/test public/
    - mv public/test public/coverage
    - cp -R build/reports/tests/test public/
    - mv public/test public/testreport
    - cd public
    - unzip $ARTIFACT
  artifacts:
    paths:
      - public

prepare_release_notes:
  stage: build
  image: registry.hub.docker.com/node:lts-alpine
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  script:
    - npm i -g downdoc
    - downdoc CHANGELOG.adoc
    - awk '/^### /{if(x)exit;x=1}x' CHANGELOG.md > release_notes.md
  artifacts:
    paths:
      - release_notes.md


release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_release_notes
      artifacts: true
    - job: build_release_artifact
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
  script:
    - echo "Creating release"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: release_notes.md
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'

upload_marketplace:
  stage: release
  needs:
    - job: build_release_artifact
      artifacts: true
    - job: release_job
      artifacts: false
  script:
    - gradle publishPlugin