sentry.dsn=https://7d4198fb3aee48c7a39623a38581d3b3@o4504774398246912.ingest.sentry.io/4504786707742720
cipipelinelint.plugin.version=0.0.21
ide.plugin.settings=Plugins...
ci.pipeline.lint.plugin.invalid.settings.title=Invalid Gitlab Settings
notification.group.ci.pipeline.lint.plugin.update=CI Pipeline Lint Plugin Update
ci.pipeline.lint.plugin.invalid.settings.host.empty=Gitlab Host is required
ci.pipeline.lint.plugin.invalid.settings.token.empty=Gitlab Token is required